### ISSUE TITLE
自定义数据集训练

### ISSUE THREAD

**Issue by houruixiang-1024** [zhangzjn/ADer#10]
![image](https://github.com/zhangzjn/ADer/assets/67264004/3ba93b65-dee9-4922-adae-1b24769b4776)
![image](https://github.com/zhangzjn/ADer/assets/67264004/22897c49-cad7-4a05-9ff3-620c0fc64c7a)
已经按数据说明进行数据处理但是还是出现这个问题，这是哪里配置没有修改正确吗

**Comment by houruixiang-1024** [comment]
![image](https://github.com/zhangzjn/ADer/assets/67264004/bb8054f3-a755-49db-99b9-5ddde9c91269)

**Comment by zhangzjn** [comment]
After ensuring the data is correct, you need to register the dataset [here](https://github.com/zhangzjn/ADer/blob/56f0caed36ba645cf37d7d9706c6494f69200af0/data/ad_dataset.py#L58) Additionally, remember to update the dataset name in the configuration file.
