### ISSUE TITLE
model文件下没有backbones文件或文件夹

### ISSUE THREAD

**Issue by 18894269590** [zhangzjn/ADer#12]
![image](https://github.com/zhangzjn/ADer/assets/67260396/69f36763-7940-459f-8734-a08fcbe9e987)
![image](https://github.com/zhangzjn/ADer/assets/67260396/7a6cc070-8bd2-42a1-8558-ca19f8b1c01b)

**Comment by zhangzjn** [comment]
The error can be resolved by deleting the specified [backbone_factory.py](https://github.com/zhangzjn/ADer/blob/main/model/backbone_factory.py). We have fixed this error.

**Comment by 18894269590** [comment]
accum = EvalAccumulatorCuda(score_min, score_max, anomap_min, anomap_max, skip_pixel_aupro=False, nstrips=50)这里面nstrips只指计算aupro时候的Number of thresholds吗？

**Comment by zhangzjn** [comment]
Please refer to the original repository at [adeval](https://github.com/winggan/adeval) and submit an issue.
