### ISSUE TITLE
without vitad/single_cls/vitad_mvtec_bs16.py

### ISSUE THREAD

**Issue by ZhuJD-China** [zhangzjn/ADer#14]

**Comment by zhangzjn** [comment]
Considering the trend towards multi-class techniques, we did not conduct benchmarked experiments on single-class methods and only provided multi-class experimental results. 

However, to accommodate researchers transitioning from single-class experiments, we have included an [example: runs_single_class.py](https://github.com/zhangzjn/ADer/blob/main/runs_single_class.py) for reference.

**Comment by ZhuJD-China** [comment]
(/16T/AIGC/AIGC_env) ubuntu@ubuntu:/16T/AIGC/ADer$ CUDA_VISIBLE_DEVICES=3 python run.py -c configs/benchmark/vitad/vitad_256_300e.py -m train
Traceback (most recent call last):
  File "/16T/AIGC/ADer/run.py", line 5, in <module>
    from trainer import get_trainer
  File "/16T/AIGC/ADer/trainer/__init__.py", line 9, in <module>
    model_lib = importlib.import_module(file.split('.')[0].replace('/', '.'))
  File "/16T/AIGC/AIGC_env/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/16T/AIGC/ADer/trainer/cfa_trainer.py", line 14, in <module>
    from model import get_model
  File "/16T/AIGC/ADer/model/__init__.py", line 86, in <module>
    model_lib = importlib.import_module(file.split('.')[0].replace('/', '.'))
  File "/16T/AIGC/AIGC_env/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/16T/AIGC/ADer/model/mambaad.py", line 24, in <module>
    from hilbert import decode, encode
ImportError: cannot import name 'decode' from 'hilbert' (/16T/AIGC/AIGC_env/lib/python3.10/site-packages/hilbert/__init__.py)             (/16T/AIGC/AIGC_env) ubuntu@ubuntu:/16T/AIGC/ADer$ pip list | grep hilbert
hilbert-toolkit                          0.1.4              /16T/AIGC/ADer/hilbert
hilbertcurve                             2.0.5
why??

**Comment by zhangzjn** [comment]
Refer to [MambaAD](https://github.com/lewandofskee/MambaAD)'s **Installation** part.

I.e., `pip3 install triton causal_conv1d mamba_ssm numpy-hilbert-curve pyzorder`
