### ISSUE TITLE
Confuse MACs and FLOPs

### ISSUE THREAD

**Issue by guojiajeremy** [zhangzjn/ADer#18]
I just found that you may mistake FLOPs by MACs. The FLOPs reported in ADer are actually MACs. As MACs~0.5*FLOPs, the reported FLOPs is around half of the real FLOPs. (Some FLOPs calculation packages also confuse this, including the one you use).

You may want to try the flops-profiler python package.

**Comment by guojiajeremy** [comment]
See this issue of the fvcore package that is used in ADer for FLOPs counting.

https://github.com/facebookresearch/fvcore/issues/69

**Comment by zhangzjn** [comment]
Yes, this issue was discussed in various fields a few years ago, but later MACs were gradually replaced by the concept of FLOPs by the research community. This default setting is also recognized by fvcore, so we retain this traditional representation.
