### ISSUE TITLE
你好，我在配属环境时候出现了些意外

### ISSUE THREAD

**Issue by rw1995** [zhangzjn/ADer#19]
![image](https://github.com/user-attachments/assets/726500d9-4489-4196-a8e7-3eea4cc6c8ba)
请问，是不是python版本不对？

**Comment by rw1995** [comment]
![image](https://github.com/user-attachments/assets/2cccab3e-79ed-45b0-8c27-4ba0a53fbecc)

**Comment by rw1995** [comment]
```python
pip install numpy-hilbert-curve==1.0.1 pyzorder==0.0.1 scikit-learn tensorboard
```

**Comment by rw1995** [comment]
```python
CUDA_VISIBLE_DEVICES=0 python run.py -c configs/invad/invad_mvtec.py -m train
```

**Comment by ctj1007** [comment]
I encountered a similar problem when configuring the environment, have you ever encountered it
![111](https://github.com/user-attachments/assets/c1082f3e-f927-4262-bddd-72339a8570d5)

**Comment by SwaggyPinqi12** [comment]
May I ask how did you solve this problem? What is the version of Python? Thank you very much
