### ISSUE TITLE
An error encountered while replicating the code

### ISSUE THREAD

**Issue by szgy66** [zhangzjn/ADer#2]
Dear author, thank you for your great work and open source its code. When I reproduced your work, I encountered an error:
`Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from trainer import get_trainer
  File "/home/401229/ADer-main/trainer/__init__.py", line 9, in <module>
    model_lib = importlib.import_module(file.split('.')[0].replace('/', '.'))
  File "/root/anaconda3/envs/ldm/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/401229/ADer-main/trainer/invad_trainer.py", line 14, in <module>
    from model import get_model
  File "/home/401229/ADer-main/model/__init__.py", line 86, in <module>
    model_lib = importlib.import_module(file.split('.')[0].replace('/', '.'))
  File "/root/anaconda3/envs/ldm/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/401229/ADer-main/model/backbone_factory.py", line 1, in <module>
    import model.backbones.pvt_v2
ModuleNotFoundError: No module named 'model.backbones'
`
I have checked the code in the **model** file and found no function related to **backbone**. How can I solve this problem? I am looking forward to your reply

**Comment by zhangzjn** [comment]
The issue arises from the import of the **model/backbone_factory.py** file. This file can be deleted to resolve the problem. This file was used during our algorithm development process when we were experimenting with other models. However, the experimental results of these models were not satisfactory, hence they can be discarded.

**Comment by szgy66** [comment]
> The issue arises from the import of the **model/backbone_factory.py** file. This file can be deleted to resolve the problem. This file was used during our algorithm development process when we were experimenting with other models. However, the experimental results of these models were not satisfactory, hence they can be discarded.

Thanks for your reply, the code has successfully started training. The article says that VITAD achieves SoTA results, but when I type ‘CUDA_VISIBLE_DEVICES=1 python run.py -c configs/vitad/vitad_mvtec.py -m train’, It will tell me that there is no ViTADTrainer module. If I type ‘CUDA_VISIBLE_DEVICES=1 python run.py -c configs/invad/invad_mvtec.py -m train’, it will run just fine. What's the problem

**Comment by zhangzjn** [comment]
Please refer to [Issue #3](https://github.com/zhangzjn/ADer/issues/3). We have fixed this problem.
