### ISSUE TITLE
请问下在文章中，这个红色框的Test Time是针对于该数据集中的相同测试数据，得到的总和测试时间吗？

### ISSUE THREAD

**Issue by rw1995** [zhangzjn/ADer#22]
![image](https://github.com/user-attachments/assets/20bacfcb-52c9-4635-a98b-af019420e575)

**Comment by zhangzjn** [comment]
是的，包含所有类别所有测试集图像的特征提取+指标评估时间

**Comment by rw1995** [comment]
好的~
