### ISSUE TITLE
METHOD doesnt exist in configs/METHOD path.

### ISSUE THREAD

**Issue by Jeriousman** [zhangzjn/ADer#23]
There is no configs/METHOD/METHOD_CFG.py when I clone your repository. Is it me or you are missing something?

Thank you.

**Comment by zhangzjn** [comment]
The capitalized terms "METHOD" and "METHOD_CFG" refer to an abstract method name and its configuration. These are modified according to the configuration file in use, such as configs/vitad/vitad_mvtec.py.

**Comment by Yoloniverse** [comment]
Thank you for the prompt answer!

**Comment by jcjlin** [comment]
Hi arthor, if i want to reproduce mambaAD on mvtec dataset and i've already cloned mambaAD under ADer, is it correct to put "mambaad_mvtec.py"  (from mambaAD) at "ader/configs/mambaad/mambaad_mvtec.py" and run CUDA_VISIBLE_DEVICES=0 python run.py -c configs/mambaad/mambaad_mvtec.py -m train?

Thanks a lot!
