### ISSUE TITLE
No module named 'hilbert'

### ISSUE THREAD

**Issue by Jeriousman** [zhangzjn/ADer#24]
I get this error below when I run `CUDA_VISIBLE_DEVICES=0 python run.py -c configs/vitad/vitad_mvtec.py -m train`

`
 File "/home/sdt/Workspace/hojun/anomaly_detection/ader/model/mambaad.py", line 24, in <module>
    from hilbert import decode, encode
ModuleNotFoundError: No module named 'hilbert'
`

And as far as I see, there is nothing like hilbert in pip.

How do I install hilbert or work around this?

Thank you.

**Comment by zhangzjn** [comment]
`pip install numpy-hilbert-curve==1.0.1`
