### ISSUE TITLE
Following MVTEC format for custom data.

### ISSUE THREAD

**Issue by Jeriousman** [zhangzjn/ADer#27]
MVTEC has mask image data. But My custom data does not have it. Must we have mask image data to run ViTAD? I just made my data in exactly the same format as MVTEC by populating mask data with just black uniform image for all image data just to follow the MVTEC data but my mask image data is just meaning less. Is it going to be okay this way or is there some way you recommend? 

Thank you in advance.

**Comment by Jeriousman** [comment]
Anybody to verify?

**Comment by zhangzjn** [comment]
It is advisable to maintain consistency with anomaly detection datasets such as MVTec AD. 

For one-class classification, you may refer to the [CifarAD](https://github.com/zhangzjn/ADer/blob/f451ac5c5aad41bf66cc1e5be0b3e886ba32bd06/data/ad_dataset.py#L384) format.

**Comment by Jeriousman** [comment]
Thank you. I will look into that

**Comment by Jeriousman** [comment]
@zhangzjn  It seems like Ader configs does not have vitad config for cifar data when it has for mvtec visa and so on.. Are you adding code for cifar soon?

**Comment by Jeriousman** [comment]
You have not uploaded confings/vitad/vitad_cifar.py.
Are you planning to do so? Thank you.

**Comment by zhangzjn** [comment]
This setting is currently not recommended, so it is not provided by default. 

However, you can easily modify the data configuration in the configuration file to enable the use of classification datasets. Here is an example:
```
		# ==> data
		self.data.type = 'CifarAD'
		self.data.root = 'data/cifar'
		self.data.type_cifar = 'cifar10'
		self.data.cls_names = ['cifar']
		self.data.uni_setting = True
		self.data.one_cls_train = True
		self.data.split_idx = 0
```
