### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by benshan123** [zhangzjn/ADer#32]
hi, thanks for your last answer. And can you kindly tell me which python version I should choose?

**Comment by benshan123** [comment]
done

**Comment by ctj1007** [comment]
I have also encountered the same problem, how do you solve it
![111](https://github.com/user-attachments/assets/fc23b37a-da7a-49af-a49b-9b930257ac9a)

**Comment by jlinjc** [comment]
hi can i know whuch python version should i use?
