### ISSUE TITLE
About single-class unsupervised defect detection

### ISSUE THREAD

**Issue by szgy66** [zhangzjn/ADer#6]
Dear author, I have successfully verified the relevant data set on your code and achieved good results. Thank you again for your contribution. But I have a question, in reality, in most cases, more single-class defect detection, the code should also be able to achieve, but your README mentioned that it is not recommended at present, can you tell me the reason？Thanks!

**Comment by zhangzjn** [comment]
Training and deploying in a single-class manner can be cumbersome, similar to fields such as classification (ImageNet-1K with 1,000 categories), detection, and segmentation (COCO with 80 categories), where it is widely accepted to use one model for many classes. 

This is also a trend towards maturity in the anomaly detection field, and historical legacy settings need to be gradually discarded.
