### ISSUE TITLE
单图推理及缺陷位置可视化

### ISSUE THREAD

**Issue by wyukai** [zhangzjn/ADer#7]
请问能否提供一下单图推理及缺陷位置可视化热力图的代码呢

**Comment by zhangzjn** [comment]
You can modify `trainer.xxx_trainer.test` for single image inference. https://github.com/zhangzjn/ADer/issues/5

**Comment by XiaobinWu1998** [comment]
> 请问能否提供一下单图推理及缺陷位置可视化热力图的代码呢

请问，你知道调整哪里才能进行单图推理得到热力图吗
