### ISSUE TITLE
Unused forward modules result in RuntimeError

### ISSUE THREAD

**Issue by ControllableGeneration** [zhangzjn/ADer#8]
I encounter this RuntimeError during parallel training:

> RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
> making sure all `forward` function outputs participate in calculating loss.

According to [this reply](https://github.com/pytorch/pytorch/issues/43259#issuecomment-964284292) and [its follow-up](https://github.com/pytorch/pytorch/issues/43259#issuecomment-1038180530), I think it is safe to multiply the unused CNN layers with zero to avoid the RuntimeError. 

Would you agree with the fix method, and would you mind me making a fix for this and making a pull request?

**Comment by zhangzjn** [comment]
In response to this issue, fundamentally, it is necessary to avoid unused modules in the model definition to ensure the standardization of the model implementation (which can lead to errors in the calculation of the model's parameter volume). Therefore, [find_unused_parameters](https://github.com/zhangzjn/ADer/blob/604047ea4694c5aeefe37139ecaf36b520121bd2/configs/__base__/cfg_common.py#L48C3-L48C46) is set to `False` by default.
